Repository Python-Markdown/markdown, pull requests merged in 2019-09, with the labels that each got.

#805 Refactor em strong to consolidate code and fix issue #792
  docs/change_log/release-3.2.md
  markdown/extensions/legacy_em.py
  markdown/inlinepatterns.py
  mkdocs.yml
  tests/test_syntax/extensions/test_legacy_em.py
  tests/test_syntax/inline/test_emphasis.py
Labels: needs-review

#859 Separate Markdown parsing in HTML to separate extension
  docs/change_log/release-3.2.md
  docs/extensions/extra.md
  docs/extensions/index.md
  docs/extensions/md_in_html.md
  markdown/extensions/extra.py
  markdown/extensions/md_in_html.py
  mkdocs.yml
  setup.py
Labels: approved

#862 Always wrap CodeHilite code in <code> tags
  docs/change_log/release-3.2.md
  docs/extensions/code_hilite.md
  markdown/extensions/codehilite.py
  tests/test_extensions.py
Labels: approved, confirmed, extension, feature
