Repository Python-Markdown/markdown, pull requests merged in 2020-06, with the labels that each got.

#984 Fix issues with complex emphasis
  docs/change_log/release-3.3.md
  markdown/extensions/legacy_em.py
  markdown/inlinepatterns.py
  tests/test_syntax/extensions/test_legacy_em.py
  tests/test_syntax/inline/test_emphasis.py
Labels: needs-review

#816 Refactor fenced code attributes
  .github/workflows/tox.yml
  .spell-dict
  docs/change_log/index.md
  docs/change_log/release-3.3.md
  docs/extensions/code_hilite.md
  docs/extensions/fenced_code_blocks.md
  markdown/extensions/attr_list.py
  markdown/extensions/codehilite.py
  markdown/extensions/fenced_code.py
  mkdocs.yml
  tests/extensions/fenced_code.html
  tests/extensions/fenced_code.txt
  tests/extensions/github_flavored.html
  tests/test_extensions.py
  tests/test_legacy.py
  tests/test_syntax/extensions/test_code_hilite.py
  tests/test_syntax/extensions/test_fenced_code.py
  tox.ini
Labels: approved

#990 Fix unescaping of HTML characters <> in CodeHilite.
  .spell-dict
  docs/change_log/release-3.3.md
  markdown/extensions/codehilite.py
  tests/test_syntax/extensions/test_code_hilite.py
Labels: requires-changes
