Repository Python-Markdown/markdown, pull requests merged in 2021-07, with the labels that each got.

#1151 document footnote's need for reset() between multiple runs
  docs/extensions/footnotes.md
Labels: docs, extension

#1152 ci(workflow): add cache to workflows using actions/setup-node
  .github/workflows/tox.yml
Labels: requires-changes

#1161 Better toc detection
  docs/change_log/index.md
  markdown/extensions/toc.py
  tests/test_syntax/extensions/test_toc.py
Labels: approved
