Repository Python-Markdown/markdown, pull requests merged in 2022-05, with the labels that each got.

#1097 Update th/td to use style attribute
  docs/change_log/index.md
  docs/change_log/release-3.4.md
  docs/extensions/tables.md
  markdown/extensions/tables.py
  tests/extensions/extra/tables.html
  tests/extensions/extra/tables.txt
  tests/test_legacy.py
  tests/test_syntax/extensions/test_tables.py
Labels: feature, extension, confirmed, approved

#1155 fixed link #1154
  docs/extensions/admonition.md
Labels: approved

#1218 Footnotes improvements
  docs/change_log/release-3.4.md
  docs/extensions/footnotes.md
  markdown/extensions/footnotes.py
  tests/test_syntax/extensions/test_footnotes.py
Labels: feature, extension, approved

#1225 Support custom CSS class on TOC element
  docs/change_log/release-3.4.md
  docs/extensions/toc.md
  markdown/extensions/toc.py
  mkdocs.yml
  tests/test_syntax/extensions/test_toc.py
Labels: approved

#1258 Pass code block's language to the specified Pygments formatter in CodeHilite
  docs/change_log/release-3.4.md
  docs/extensions/code_hilite.md
  markdown/extensions/codehilite.py
  tests/test_syntax/extensions/test_code_hilite.py
  tests/test_syntax/extensions/test_fenced_code.py
Labels: approved

#1259 Drop support for PY36
  .coveragerc
  .github/workflows/tox.yml
  docs/change_log/release-3.4.md
  markdown/__init__.py
  markdown/__meta__.py
  markdown/pep562.py
  markdown/util.py
  setup.py
  tox.ini
Labels: requires-changes, process

#1262 Add None check to PrettifyTreeprocessor
  docs/change_log/release-3.4.md
  markdown/treeprocessors.py
Labels: approved

#1260 Remove previously deprecated objects.
  docs/change_log/release-3.4.md
  markdown/__init__.py
  markdown/blockparser.py
  markdown/core.py
  markdown/extensions/__init__.py
  markdown/extensions/smarty.py
  markdown/inlinepatterns.py
  markdown/treeprocessors.py
  markdown/util.py
  tests/test_apis.py
Labels: needs-review
