Repository Python-Markdown/markdown, pull requests merged in 2025-03, with the labels that each got.

#1487 Add Python 3.13 and drop Python 3.8
  .github/workflows/tox.yml
  pyproject.toml
  tox.ini
Labels: approved

#1516 Use PEP 639 license expressions in project metadata
  pyproject.toml
Labels: requires-changes, confirmed, process

#1510 Optimize raw HTML post-processor
  docs/changelog.md
  markdown/postprocessors.py
Labels: needs-review, requires-changes
